import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { fetchImageModels, getModelById, DEFAULT_IMAGE_MODELS } from "@/lib/models";
import type { Metadata } from "next";

interface SharePageProps {
  params: Promise<{ id: string }>;
}

async function getGeneration(shareId: string) {
  const supabase = await createClient();
  const { data } = await supabase
    .from("generations")
    .select("*")
    .eq("share_id", shareId)
    .eq("is_public", true)
    .single();
  return data;
}

function getModelName(modelId: string): string {
  const model = getModelById(modelId);
  if (model) return model.name;
  const fallback = DEFAULT_IMAGE_MODELS.find((m) => m.id === modelId);
  return fallback?.name || modelId.split("/").pop() || modelId;
}

export async function generateMetadata({ params }: SharePageProps): Promise<Metadata> {
  const { id } = await params;
  const generation = await getGeneration(id);

  if (!generation) {
    return { title: "Not Found - PicDuet" };
  }

  await fetchImageModels();
  const modelAName = getModelName(generation.model_a);
  const modelBName = getModelName(generation.model_b);
  const title = `${modelAName} vs ${modelBName} - PicDuet`;
  const description = `"${generation.prompt}" — See which AI model won this image duel on PicDuet.`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      images: generation.image_a_url ? [generation.image_a_url] : [],
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: generation.image_a_url ? [generation.image_a_url] : [],
    },
  };
}

export default async function SharePage({ params }: SharePageProps) {
  const { id } = await params;
  const generation = await getGeneration(id);

  if (!generation) {
    notFound();
  }

  await fetchImageModels();
  const modelAName = getModelName(generation.model_a);
  const modelBName = getModelName(generation.model_b);
  const winnerIs = generation.selected_winner;

  return (
    <div className="flex min-h-screen flex-col bg-background">
      {/* Header */}
      <header className="border-b border-border bg-background">
        <div className="mx-auto flex h-14 max-w-7xl items-center justify-between px-4 sm:px-6">
          <a href="/generate">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/logo.png" alt="PicDuet" className="h-8" />
          </a>
          <a
            href="/auth/login"
            className="rounded-xl bg-accent px-4 py-2 text-sm font-medium text-accent-text transition-opacity hover:opacity-90"
          >
            Try PicDuet
          </a>
        </div>
      </header>

      {/* Content */}
      <div className="mx-auto w-full max-w-5xl px-4 py-8 sm:px-6">
        {/* Prompt */}
        <div className="mb-6 text-center">
          <p className="text-sm text-tertiary">Prompt</p>
          <p className="mt-1 text-lg text-foreground">&ldquo;{generation.prompt}&rdquo;</p>
        </div>

        {/* Duel images */}
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-[1fr_auto_1fr] sm:items-start">
          {/* Model A */}
          <div
            className={`flex flex-col rounded-2xl border p-4 ${
              winnerIs === "a"
                ? "border-2 border-winner"
                : "border-border"
            }`}
          >
            <div className="flex items-center gap-2">
              <span className="h-2 w-2 rounded-full bg-emerald-400" />
              <span className="text-sm font-medium text-foreground">
                {modelAName}
              </span>
              {winnerIs === "a" && (
                <span className="ml-auto rounded-full bg-winner/10 px-2 py-0.5 text-xs font-medium text-winner">
                  Winner
                </span>
              )}
            </div>
            <div className="mt-3 overflow-hidden rounded-xl border border-border">
              <div className="aspect-square w-full">
                {generation.image_a_url ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={generation.image_a_url}
                    alt={`Generated by ${modelAName}`}
                    className="h-full w-full object-cover"
                  />
                ) : (
                  <div className="flex h-full items-center justify-center bg-surface text-sm text-tertiary">
                    Image unavailable
                  </div>
                )}
              </div>
            </div>
          </div>

          <div className="flex items-center justify-center py-4 sm:pt-16">
            <span className="text-sm text-tertiary">vs</span>
          </div>

          {/* Model B */}
          <div
            className={`flex flex-col rounded-2xl border p-4 ${
              winnerIs === "b"
                ? "border-2 border-winner"
                : "border-border"
            }`}
          >
            <div className="flex items-center gap-2">
              <span className="h-2 w-2 rounded-full bg-amber-400" />
              <span className="text-sm font-medium text-foreground">
                {modelBName}
              </span>
              {winnerIs === "b" && (
                <span className="ml-auto rounded-full bg-winner/10 px-2 py-0.5 text-xs font-medium text-winner">
                  Winner
                </span>
              )}
            </div>
            <div className="mt-3 overflow-hidden rounded-xl border border-border">
              <div className="aspect-square w-full">
                {generation.image_b_url ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={generation.image_b_url}
                    alt={`Generated by ${modelBName}`}
                    className="h-full w-full object-cover"
                  />
                ) : (
                  <div className="flex h-full items-center justify-center bg-surface text-sm text-tertiary">
                    Image unavailable
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* CTA */}
        <div className="mt-10 text-center">
          <a
            href="/auth/login"
            className="inline-flex rounded-xl bg-accent px-6 py-3 text-sm font-medium text-accent-text transition-opacity hover:opacity-90"
          >
            Try PicDuet — Compare AI Image Models
          </a>
          <p className="mt-3 text-xs text-tertiary">
            Send the same prompt to two AI models. Pick the winner.
          </p>
        </div>
      </div>
    </div>
  );
}
