"use client";

import ModelSelector from "./ModelSelector";

interface ImageCardProps {
  imageUrl: string | null;
  error?: string;
  modelId: string;
  modelName: string;
  loading: boolean;
  accent: "a" | "b";
  selected: boolean;
  onSelect: () => void;
  onModelChange: (modelId: string) => void;
  hideModelSelector?: boolean;
}

export default function ImageCard({
  imageUrl,
  error,
  modelId,
  modelName,
  loading,
  accent,
  selected,
  onSelect,
  onModelChange,
  hideModelSelector,
}: ImageCardProps) {
  const dotColor = accent === "a" ? "bg-emerald-400" : "bg-amber-400";
  const blindLabel = accent === "a" ? "Model A" : "Model B";

  return (
    <div
      className={`flex flex-1 flex-col rounded-2xl border p-4 transition-colors ${
        selected ? "border-2 border-winner" : "border-border"
      }`}
    >
      {/* Model dropdown or blind label */}
      {hideModelSelector ? (
        <div className="flex items-center gap-2 rounded-xl border border-border-hover bg-surface py-3 px-3.5">
          <span className={`h-2.5 w-2.5 rounded-full ${dotColor}`} />
          <span className="text-sm font-medium text-foreground">
            {selected ? (
              <span className="animate-reveal inline-block">{modelName}</span>
            ) : (
              blindLabel
            )}
          </span>
        </div>
      ) : (
        <ModelSelector value={modelId} onChange={onModelChange} dotColor={dotColor} />
      )}

      {/* Image area */}
      <div className={`mt-3 overflow-hidden rounded-xl ${loading ? "loading-gradient-border p-px" : "border border-border"}`}>
        <div className={`aspect-square w-full ${loading ? "rounded-[11px]" : ""}`}>
          {loading ? (
            <div className="flex h-full flex-col items-center justify-center rounded-[11px] bg-surface">
              {/* Spinning ring */}
              <div className="relative h-14 w-14">
                <svg className="loading-ring h-full w-full" viewBox="0 0 48 48" fill="none">
                  <circle cx="24" cy="24" r="20" stroke="var(--border-hover)" strokeWidth="2" />
                  <path d="M44 24a20 20 0 01-20 20" stroke="var(--text-secondary)" strokeWidth="2" strokeLinecap="round" />
                </svg>
                {/* Center sparkle */}
                <div className="loading-fade absolute inset-0 flex items-center justify-center">
                  <svg className="h-5 w-5 text-muted" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 00-2.455 2.456z" />
                  </svg>
                </div>
              </div>
              <span className="mt-4 text-sm text-tertiary loading-fade">Generating...</span>
            </div>
          ) : error ? (
            <div className="flex h-full flex-col items-center justify-center gap-2 bg-surface p-6">
              <svg
                className="h-8 w-8 text-red-400/60"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={1.5}
                  d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z"
                />
              </svg>
              <p className="text-center text-sm leading-relaxed text-red-400/80">
                {error}
              </p>
            </div>
          ) : imageUrl ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={imageUrl}
              alt={`Generated by ${modelName}`}
              className="h-full w-full object-cover"
            />
          ) : (
            <div className="flex h-full flex-col items-center justify-center gap-2 bg-surface">
              <svg
                className="h-12 w-12 text-border-hover"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth={1}
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M2.25 15.75l5.159-5.159a2.25 2.25 0 013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909M3.75 21h16.5A2.25 2.25 0 0022.5 18.75V5.25A2.25 2.25 0 0020.25 3H3.75A2.25 2.25 0 001.5 5.25v13.5A2.25 2.25 0 003.75 21z"
                />
              </svg>
              <span className="text-sm text-tertiary">Awaiting generation</span>
            </div>
          )}
        </div>
      </div>

      {/* Action buttons */}
      {imageUrl && !loading && (
        <div className="mt-3 flex gap-2">
          <button
            onClick={onSelect}
            className={`flex-1 rounded-xl border px-5 py-2.5 text-sm font-medium transition-colors ${
              selected
                ? "border-winner bg-winner/10 text-winner"
                : "border-border text-muted hover:border-border-hover hover:text-foreground"
            }`}
          >
            {selected ? "Selected" : "Pick this one"}
          </button>
          <a
            href={imageUrl}
            download={`picduet-${accent}-${Date.now()}.png`}
            className="flex items-center justify-center rounded-xl border border-border px-3 py-2.5 text-muted transition-colors hover:border-border-hover hover:text-foreground"
          >
            <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
            </svg>
          </a>
        </div>
      )}
    </div>
  );
}
